services:
- docker
env:
  global:
    - secure: "OtxRw9MtJrc7EiXg+fLU+C3PUcinLb3AJ41AkGORfMfDiQDunItbiSdB7Ep3GKY3AFfAg8Z9E30uiQwxDecef9VU53wYAWCryvRSqTULfjk9fn/B6sPzlx/CehocY6iYf8A/KlFYcJ6mwx7bWKysYuADKoKLQPjI5hI5XK1TIGgLIPr6KdDLP/oFgwBGPxQkxqsAjpMQKwSsE+wC7JGXdAhDvpFadV98TKt75x/5xR+8vJR1SCNVWR0Q6qg4iwI2pTh+Vt7d+QOkItyB68wxv9+wkAigNf2RKG7ShDsytQC2y8PhjudvFDfKw9+7KBO9PqAqhmlHkR2ZQUKUOck7mm+5y9vNdkYqf8Rcsh4wjb9WlptgssLXAKelY3ThZHvlr4L14bTiDLLiu3s8xj3D3F8xg6jKiMIuY3CEAYhtwByJZlSx+6jxPwTXE54r2jenERfvM10vLhjO7b10JtKOBd+9AdnTb32K9JAoOMpjgKkManBTCDCjy3ba6Lxp4I6SpbVmiu12IUvg6HbTAkuYMX5MWD5J/DFXiXYhLN/BhH/et0koe76o+/vBSvLoMKxEyrCQ31Wx77ysuiMozCYb+wesEMpvtk+xKVfinZMQ/mu04dQLLRlSqPleUzhM5GeL9rVMzNHsA1Lo6BJOREoWf4l51rqJPX7Mixc7j+YVd5A="
    - secure: "bk4G/hTxzgyrkg++QMUXPI6raPQMKvp6VMpm0BCOpG61aCS3uDV9zJNe0fAKOa/35NlG8DtWJIYPyO9XpVcnIa947UZrP/hQrveQKGaLrcrfmXA//FyAgda3Lw2IBhfqU8T2agSHuDSlDrKtfJQxWry3xf8ppoLC02oCrgLxNgUUGc4d/YKlac/z7IFKtrzDTxl6Ucqhysbs8GecUBZxPewMZ8jgLJRZZ7qFKPBNuv0nG7RsuC93X+1q6Mm76MITFkoFfJPtctGdF+O0N7r0OVUSwBBIbXXaVS0Bh9aqz/KlbGJahIEOKWsjdbRASJ00WhX2UZMsEc6jnz1v3cPdQqNZjpNz9SLVbaeM7cDUO12m4QxHLAzcyvSmKbakaG982TepXg6lYqYaxZoGlIIRaWfZYRkoyf9gZX/nJY3uL7AHfel7pyFd2uOBvkSZ8hIga6FPIBOoPAeTSpXwU8qIPEYcjBBri6P/iONE7GUX4b8rav/ItlIzJKp17aJgftrijJwm3e3eJ4Eqkp8H5tejNLz1FY7b7asSDyZY1SQkajxQV1JYHnjhfQg9EA7a0MQO6+2kJT4T1ag3U5BAP070rbuQ6S0UwFN0LJG9Wsqt37R+lKVZwR5w6kv/0G7n8SwVzQ8SssRDTnaJcbU/+oLYdUGnu2LzzkQbu2ryUrFuPxo="
script:
- echo $QUAYL
- export SAVE=$PWD cnt="ubucphctr" slim=".slim"
- "./scripts/slimceph"
- docker tag ceph/daemon.slim ${cnt}${slim}
before_deploy:
- cd
- wget `curl -s https://api.github.com/repos/appc/docker2aci/releases | grep browser_download_url
  | head -n 1 | cut -d '"' -f 4` -O d2a.tar.gz
- tar -zxf d2a.tar.gz && rm d2a.tar.gz && d2a=`ls | grep "docker2aci*"` && d2a=`basename  $d2a`
  && alias d2a='${PWD}/${d2a}/docker2aci'
- docker save -o ${cnt}${slim}.tar ${cnt}${slim}
- "${PWD}/${d2a}/docker2aci ${cnt}${slim}.tar"
- xz -9 -c ${cnt}${slim}.tar > ${cnt}${slim}.tar.xz
- docker login -u $quaylogin -p $quaypsw quay.io
- docker tag ${cnt}${slim} quay.io/natostanco/$cnt
- docker push quay.io/natostanco/$cnt
deploy:
  provider: releases
  api_key:
    secure: kQf2HeVQyCTgEwVv9pOV3RSTReoIlkf/1Xl2TRquXwC8ZQDNw+BKfsNM6y7e/ApkFoFVK7fjE/Ct8r7IJ9IEre+lg7n5NkW3aSwimzlgZLdk+ePihaKs2SIpDIf29LogcRznP96CDbhR7jR7P3A0KnUc2VDw6EhlDRcfzkksI/bEttOkG3Qi2SkeINxTbIv02/Ty00qYzv93ekC4mn7L9mx0PkErvSc6uFAubcvepfpxX5/ReLr2f8L2/jy0SV0l0JhyE+B7IW8576FAN8v5u1DAnfkKQiaA2alEh3u7+JAuF1z9u2uNgJO1WClNTILL8WjE/vBOayJb6DIHcILpSAlXMVZEaJYGdrZBTCuI9d34qUrGR59iBXXGnyXV7Hh9l+UmpUqFdwczckX2Ct6j8qXraIsYc1ykYrKC/2uq2LDYnMiCGk2IzcKhteI9iWjq+vm4IvfrmHZ/zgozM4UWiN6vCCw8vFJP2KRKjqlMdPxUy/7gmqHUOyU7Rts+PCQ9sZ61shVvpValGUCquKF5k7f8ESPBV8q4BUH1T7lv7iX80W5sfea1dGbYDG+8hgYQpWg8wRsJ9T22pIP91ioEvs3prg1ja00hu0uQp1kBjwSmX7idANw0DFTMba3bo28Zp3V6hOyUSJhNgwQDM0T7Uq1vmNLj2E008SG21dAehuM=
  file:
  - ${cnt}${slim}.tar.xz 
  - ${cnt}${slim}-latest.aci 
  skip_cleanup: true
  on:
    tags: true
