services:
- docker
env:
- secure: "BPiSDp+Gv1x5hnkc0EkisyMqqQf91Tdxaz9vAJ2A7gonfTltF7K1BLxWYo/5xehzrE/A3N4K+GnYSSqfoytG2VwUGANBWjNbjKWEpcr2h8jcq9V9eBtG0lMpukEHEVC6ijXEsyjDeH2DKh5hZTVyUovKuCdPSIejNHuZe7tUhQqopn58EKWagXGoNUlzyY9qGUZBx2GmPqaJhTA0995mC13NTrk7q0oRyUFAb+xcE2PpifpdgAXsxWqfeUg0jz7kOec7pK7bdXMAAkSAoEUH1UVtC+XgerirW8JXSAwSNoxuTpwE9fsZq9Mlm5WO+ZUSaxsIvV1XTHB3TKeUCP3nU7KXMXmAZVc9EA0O+pI7X68zIVGmagketz2/f/l18ELQmMxp/IHPpJ6jxWDvUAsNRWKlPTjdYsgp4k4rd4Z2fN/BJHgm5ea/goD5cO9Xs4DolVKhrIa0MkIkcZnZhR3/2v3ecLX2myN3yGAFof9PPcEyI8KVVBOB8lUInjSvOoOnryACZWf71WyHx1wtSohzQt2DsX2LB/dVTYc2oyiHGaju5ee5WU69Clk4UFz1wZ7uyxnxN3I9dT6Iz97LhghMyXmZazE7fT+cx0Pcvv2oFobi3k23FyA4RBeC04Pyy5GKP86YpP2hrrZ/9+lpX6kdcJuXw57nntroCGvrmCEEoW0="
- secure: "bk4G/hTxzgyrkg++QMUXPI6raPQMKvp6VMpm0BCOpG61aCS3uDV9zJNe0fAKOa/35NlG8DtWJIYPyO9XpVcnIa947UZrP/hQrveQKGaLrcrfmXA//FyAgda3Lw2IBhfqU8T2agSHuDSlDrKtfJQxWry3xf8ppoLC02oCrgLxNgUUGc4d/YKlac/z7IFKtrzDTxl6Ucqhysbs8GecUBZxPewMZ8jgLJRZZ7qFKPBNuv0nG7RsuC93X+1q6Mm76MITFkoFfJPtctGdF+O0N7r0OVUSwBBIbXXaVS0Bh9aqz/KlbGJahIEOKWsjdbRASJ00WhX2UZMsEc6jnz1v3cPdQqNZjpNz9SLVbaeM7cDUO12m4QxHLAzcyvSmKbakaG982TepXg6lYqYaxZoGlIIRaWfZYRkoyf9gZX/nJY3uL7AHfel7pyFd2uOBvkSZ8hIga6FPIBOoPAeTSpXwU8qIPEYcjBBri6P/iONE7GUX4b8rav/ItlIzJKp17aJgftrijJwm3e3eJ4Eqkp8H5tejNLz1FY7b7asSDyZY1SQkajxQV1JYHnjhfQg9EA7a0MQO6+2kJT4T1ag3U5BAP070rbuQ6S0UwFN0LJG9Wsqt37R+lKVZwR5w6kv/0G7n8SwVzQ8SssRDTnaJcbU/+oLYdUGnu2LzzkQbu2ryUrFuPxo="
script:
- export SAVE=$PWD cnt="ubucphctr" slim=".slim"
- "./scripts/slimceph"
- docker tag ceph/daemon.slim ${cnt}${slim}
before_deploy:
- cd
- wget `curl -s https://api.github.com/repos/appc/docker2aci/releases | grep browser_download_url
  | head -n 1 | cut -d '"' -f 4` -O d2a.tar.gz
- tar -zxf d2a.tar.gz && rm d2a.tar.gz && d2a=`ls | grep "docker2aci*"` && d2a=`basename  $d2a`
  && alias d2a='${PWD}/${d2a}/docker2aci'
- docker save -o ${cnt}${slim}.tar ${cnt}${slim}
- "${PWD}/${d2a}/docker2aci ${cnt}${slim}.tar"
- xz -9 -c ${cnt}${slim}.tar > ${cnt}${slim}.tar.xz
- docker login -u $quaylogin -p $quaypsw quay.io
- docker tag ${cnt}${slim} quay.io/natostanco/$cnt
- docker push quay.io/natostanco/$cnt
deploy:
  provider: releases
  api_key:
    secure: kQf2HeVQyCTgEwVv9pOV3RSTReoIlkf/1Xl2TRquXwC8ZQDNw+BKfsNM6y7e/ApkFoFVK7fjE/Ct8r7IJ9IEre+lg7n5NkW3aSwimzlgZLdk+ePihaKs2SIpDIf29LogcRznP96CDbhR7jR7P3A0KnUc2VDw6EhlDRcfzkksI/bEttOkG3Qi2SkeINxTbIv02/Ty00qYzv93ekC4mn7L9mx0PkErvSc6uFAubcvepfpxX5/ReLr2f8L2/jy0SV0l0JhyE+B7IW8576FAN8v5u1DAnfkKQiaA2alEh3u7+JAuF1z9u2uNgJO1WClNTILL8WjE/vBOayJb6DIHcILpSAlXMVZEaJYGdrZBTCuI9d34qUrGR59iBXXGnyXV7Hh9l+UmpUqFdwczckX2Ct6j8qXraIsYc1ykYrKC/2uq2LDYnMiCGk2IzcKhteI9iWjq+vm4IvfrmHZ/zgozM4UWiN6vCCw8vFJP2KRKjqlMdPxUy/7gmqHUOyU7Rts+PCQ9sZ61shVvpValGUCquKF5k7f8ESPBV8q4BUH1T7lv7iX80W5sfea1dGbYDG+8hgYQpWg8wRsJ9T22pIP91ioEvs3prg1ja00hu0uQp1kBjwSmX7idANw0DFTMba3bo28Zp3V6hOyUSJhNgwQDM0T7Uq1vmNLj2E008SG21dAehuM=
  file:
  - ${cnt}${slim}.tar.xz 
  - ${cnt}${slim}-latest.aci 
  skip_cleanup: true
  on:
    tags: true
