#!/bin/bash
#slimceph
docker pull ceph/daemon
docker run --name ceph-ip --entrypoint /bin/bash ceph/daemon -c "apt-get update && apt-get install iptables -y -q"
docker commit --change='ENTRYPOINT ["/entrypoint.sh"]' ceph-ip ceph/daemon:ip
mkdir -p ${SAVE}/etc ${SAVE}/var
sudo ./docker-slim --debug build \
--continue-after 60 \
--http-probe \
--mount ${SAVE}/etc:/etc/ceph \
--mount ${SAVE}/var:/var/lib/ceph \
--mount ${SAVE}/scripts:/scripts \
--include-path /etc/confd \
--include-path /var/log/ceph \
--include-path /usr/lib/ceph \
--include-path /tmp \
--entrypoint /bin/bash \
ceph/daemon:ip &> /dev/null &

sleep 5

docker exec -it $(docker ps | grep dockerslim | awk '{print $1}') /scripts/testceph

while [[ $( docker images | grep "ceph/daemon.slim" | wc -l ) -ne 1 ]]
do 
sleep 5
done
