#!/bin/bash
docker pull ceph/daemon
sudo ./docker-slim --debug build \
--continue-after 60 \
--http-probe \
--mount ../etc:/etc/ceph \
--mount ../var:/var/lib/ceph \
--mount ../scripts:/scripts \
--include-path /etc/confd \
--include-path /var/log/ceph \
--include-path /tmp \
ceph/daemon &> /dev/null &

sleep 5
echo $(docker ps)
docker exec -it $(docker ps | grep dockerslim | awk '{print $1}') /scripts/testceph

sleep 55
